# Generated by Django 4.0.4 on 2022-05-15 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VihicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('vehicle_type', models.CharField(blank=True, choices=[('Two wheelers', 'Two wheelers'), ('There wheelers', 'There wheelers'), ('Four wheelers', 'Four wheelers')], max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('published', models.BooleanField(default=True, verbose_name='Published on')),
            ],
        ),
    ]
