# Generated by Django 4.0.4 on 2022-05-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VihicleData',
            new_name='VehicleData',
        ),
    ]
